import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { Prisma, TeamMemberStatus } from "@1toufang/database/client";
import { AuthenticatedUser } from "../common/types/authenticated-request";
import { DatabaseService } from "../database/database.service";
import { CreateCopywritingDto, GenerateCopywritingDto, UpdateCopywritingDto } from "./dto";

@Injectable()
export class CopywritingsService {
  constructor(private readonly db: DatabaseService) {}

  async list(user: AuthenticatedUser) {
    const teamId = await this.resolveTeamId(user);
    const copywritings = await this.db.copywriting.findMany({
      where: { teamId },
      orderBy: { updatedAt: "desc" }
    });
    const copywritingIds = copywritings.map((row) => row.id);
    const [creatives, createdLogs] = await Promise.all([
      this.db.adCreative.findMany({
        where: { teamId },
        select: { id: true, config: true, status: true }
      }),
      copywritingIds.length
        ? this.db.auditLog.findMany({
            where: {
              teamId,
              entityType: "copywriting",
              entityId: { in: copywritingIds },
              action: "COPYWRITING_CREATED"
            },
            include: { actor: { include: { profile: true } } },
            orderBy: { createdAt: "asc" }
          })
        : []
    ]);
    const createdById = new Map(createdLogs.map((log) => [log.entityId ?? "", log.actor]));
    const statsByCopywriting = new Map<string, { adCount: number; rejectedCount: number }>();

    for (const creative of creatives) {
      const copywritingId = stringValue(asRecord(creative.config).copywritingId);
      if (!copywritingId) continue;
      const stats = statsByCopywriting.get(copywritingId) ?? { adCount: 0, rejectedCount: 0 };
      stats.adCount += 1;
      if (isRejectedCreativeStatus(creative.status)) stats.rejectedCount += 1;
      statsByCopywriting.set(copywritingId, stats);
    }

    return copywritings.map((row) => {
      const stats = statsByCopywriting.get(row.id) ?? { adCount: 0, rejectedCount: 0 };
      return {
        ...row,
        creator: createdById.get(row.id) ?? null,
        source: taggedValue(row.tags, "source") ?? "manual",
        languages: taggedValues(row.tags, "lang"),
        adCount: stats.adCount,
        rejectedCount: stats.rejectedCount,
        rejectionRate: stats.adCount ? round((stats.rejectedCount / stats.adCount) * 100, 2) : 0
      };
    });
  }

  async create(dto: CreateCopywritingDto, user: AuthenticatedUser) {
    const teamId = dto.teamId ?? (await this.resolveTeamId(user));
    const copywriting = await this.db.copywriting.create({
      data: {
        teamId,
        name: dto.name,
        primaryText: dto.primaryText,
        headline: dto.headline,
        description: dto.description,
        tags: dto.tags ?? [],
        remarks: dto.remarks
      }
    });

    await this.audit(user.id, teamId, "COPYWRITING_CREATED", copywriting.id, {
      name: copywriting.name,
      headline: copywriting.headline
    });

    return copywriting;
  }

  async generate(dto: GenerateCopywritingDto, user: AuthenticatedUser) {
    await this.resolveTeamId(user);
    const product = clean(dto.product) ?? "产品";
    const audience = clean(dto.audience) ?? "目标用户";
    const offer = clean(dto.offer) ?? "限时优惠";
    const language = clean(dto.language) ?? "zh-CN";
    const tone = clean(dto.tone) ?? "performance";
    const source = clean(dto.source) ?? "fixed-template";
    const isEnglish = language.toLowerCase().startsWith("en");

    return {
      name: isEnglish ? `${product} - ${tone} copy` : `${product} - ${tone} 文案`,
      headline: isEnglish ? `${product} built for ${audience}` : `${product}，为${audience}准备`,
      description: isEnglish ? `${offer}. Fast setup, clear value, measurable results.` : `${offer}，快速上手，效果清晰可追踪。`,
      primaryText: isEnglish
        ? `Looking for a better option for ${audience}? ${product} helps you move faster with a simple setup and focused results. ${offer}.`
        : `${audience}正在寻找更高效的选择？${product} 用更简单的方式帮你快速开始，并把效果看得更清楚。${offer}，现在就可以体验。`,
      remarks: isEnglish
        ? `Generated by fixed template. Tone: ${tone}. Source: ${source}.`
        : `固定模板生成。语气：${tone}。来源：${source}。`,
      tags: [`source:${source}`, `lang:${language}`, "generated"]
    };
  }

  async duplicate(id: string, user: AuthenticatedUser) {
    const teamId = await this.resolveTeamId(user);
    const source = await this.ensureCopywriting(id, teamId);
    const copywriting = await this.db.copywriting.create({
      data: {
        teamId,
        name: `${source.name} 副本`,
        primaryText: source.primaryText,
        headline: source.headline,
        description: source.description,
        tags: Array.from(new Set([...(source.tags ?? []), "copied"])),
        remarks: source.remarks
      }
    });

    await this.audit(user.id, teamId, "COPYWRITING_DUPLICATED", copywriting.id, {
      sourceId: source.id,
      name: copywriting.name
    });

    return copywriting;
  }

  async update(id: string, dto: UpdateCopywritingDto, user: AuthenticatedUser) {
    const teamId = await this.resolveTeamId(user);
    await this.ensureCopywriting(id, teamId);
    const copywriting = await this.db.copywriting.update({
      where: { id },
      data: {
        name: dto.name,
        primaryText: dto.primaryText,
        headline: dto.headline,
        description: dto.description,
        tags: dto.tags,
        remarks: dto.remarks
      }
    });

    await this.audit(user.id, teamId, "COPYWRITING_UPDATED", copywriting.id, {
      name: copywriting.name,
      headline: copywriting.headline
    });

    return copywriting;
  }

  async remove(id: string, user: AuthenticatedUser) {
    const teamId = await this.resolveTeamId(user);
    const copywriting = await this.ensureCopywriting(id, teamId);
    await this.db.copywriting.delete({ where: { id } });
    await this.audit(user.id, teamId, "COPYWRITING_DELETED", id, {
      name: copywriting.name,
      headline: copywriting.headline
    });
    return { ok: true };
  }

  private async ensureCopywriting(id: string, teamId: string) {
    const copywriting = await this.db.copywriting.findFirst({ where: { id, teamId } });
    if (!copywriting) throw new NotFoundException("Copywriting not found");
    return copywriting;
  }

  private async resolveTeamId(user: AuthenticatedUser) {
    if (user.teamId) return user.teamId;

    const membership = await this.db.teamMember.findFirst({
      where: { userId: user.id, status: TeamMemberStatus.ACTIVE },
      orderBy: { createdAt: "asc" }
    });
    if (!membership) {
      throw new BadRequestException("User does not belong to a team");
    }
    return membership.teamId;
  }

  private audit(actorId: string, teamId: string, action: string, entityId: string, metadata: Record<string, unknown>) {
    return this.db.auditLog.create({
      data: {
        actorId,
        teamId,
        action,
        entityType: "copywriting",
        entityId,
        metadata: toJson(metadata)
      }
    });
  }
}

function toJson(value: Record<string, unknown>) {
  return value as Prisma.InputJsonValue;
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>) : {};
}

function stringValue(value: unknown) {
  return typeof value === "string" && value.trim() ? value.trim() : undefined;
}

function taggedValue(tags: string[], key: string) {
  const prefix = `${key}:`;
  const tag = tags.find((item) => item.startsWith(prefix));
  return tag ? tag.slice(prefix.length) : undefined;
}

function taggedValues(tags: string[], key: string) {
  const prefix = `${key}:`;
  return tags.filter((item) => item.startsWith(prefix)).map((item) => item.slice(prefix.length));
}

function isRejectedCreativeStatus(status: string) {
  const normalized = status.toLowerCase();
  return normalized.includes("reject") || normalized.includes("fail") || normalized.includes("disapproved");
}

function clean(value?: string) {
  const normalized = value?.trim();
  return normalized || undefined;
}

function round(value: number, digits: number) {
  const factor = 10 ** digits;
  return Math.round((value + Number.EPSILON) * factor) / factor;
}
