-- CreateEnum
CREATE TYPE "TeamType" AS ENUM ('PERSONAL', 'TEAM');

-- CreateEnum
CREATE TYPE "TeamStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'EXPIRED');

-- AlterTable
ALTER TABLE "User" ADD COLUMN "accessExpiresAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN "maxTeamCount" INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "Team" ADD COLUMN "type" "TeamType" NOT NULL DEFAULT 'PERSONAL';
ALTER TABLE "Team" ADD COLUMN "seatLimit" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Team" ADD COLUMN "status" "TeamStatus" NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "Team" ADD COLUMN "expiresAt" TIMESTAMP(3);
ALTER TABLE "Team" ADD COLUMN "notes" TEXT;
